### ISSUE TITLE
How does the expiration time work?

### ISSUE THREAD

**Issue by davidxd33** [cosenary/Simple-PHP-Cache#12]
Is it measured in seconds, milliseconds, minutes, hours? If I set $c->store('text', 'Hello', 5000) will that cache be stored for 5 seconds before expiring? After it expires, does it get deleted?

**Comment by TiagoGouvea** [comment]
@davidxd33 
I commited some changes to return just nonexpired data. You can check it at https://github.com/TiagoGouvea/Simple-PHP-Cache
It don't will erase expired data, but will not return it when you need it.
You can also call eraseExpired() once in a while to remove then.
