### ISSUE TITLE
consider adding composer.json

### ISSUE THREAD

**Issue by modstudio** [cosenary/Simple-PHP-Cache#16]
```json
{
    "name": "cosenary/Simple-PHP-Cache",
    "type": "library",
    "require": {
        "php": ">=5.2.0"
    },
    "autoload": {
        "classmap": [
            "."
        ]
    }
}
```
There are more variables to add, but this is the basics :) I would like to implement this with composer.

**Comment by cosenary** [comment]
Thanks for your template, I just added the `composer.json` to the project ([Packagist](https://packagist.org/packages/cosenary/simple-php-cache)).
