### ISSUE TITLE
Cache expiration does not seems to work

### ISSUE THREAD

**Issue by danielfollow** [cosenary/Simple-PHP-Cache#25]
Tried creating a cache with 5 minutes expiration but it does not seems to update the new value after 5 minutes.

example:

```
$cache->setCache('title');
$cache->eraseExpired();

if ( $cache->isCached('main-header') ) {
  print_r($cache->retrieve('main-header'))
} else {
  $cache->store('main-header', "new header title", 360000);
}
```

**Comment by mtreik** [comment]
Note that the expiry time is indicated in seconds.

In your example code, you indicated 360000 seconds, the equivalent to 100 hours.
